pipeline {
    agent any
    tools {
        maven 'Maven 3.3.9'
        jdk 'jdk8'
    }
    stages {
        stage ('Initialize') {
            steps {
                script {
                    checkout scm
                    dockerImage = docker.build("my-image:${env.BUILD_ID}", "-f Dockerfile ./initial") 
                }
            }
        }
    }
}
